version: '3.8'
services:
  reverse-proxy:
    image: traefik:v2.6
    command:
      - "--api.debug=true"
      - "--api.dashboard=true"
      - "--api"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.openvpn.address=:1194"

    ports:
      - "80:80"
      - "1194:1194"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${HASH_ADMIN_PASS}"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - vpn-net
      - proxy

  checker:
    image: explabs/ad-ctf-paas-checker
    container_name: checker
    restart: unless-stopped
    environment:
      - ADMIN_PASS=admin
      - MONGODB=mongo:27017
    volumes:
      - ./scripts/checkers/:/checker/scripts/
      - ./configs/config.yml:/checker/config.yml
    extra_hosts:
      - "naliway:172.17.0.1"
    networks:
      - service-net
    depends_on:
      - rabbit

  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=service
      - RABBITMQ_DEFAULT_PASS=${ADMIN_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - service-net

  exploits:
    image: explabs/ad-ctf-paas-exploits
    container_name: exploits
    restart: unless-stopped
    environment:
      - ADMIN_PASS=admin
      - MONGODB=mongo:27017
    depends_on:
      - rabbit
    volumes:
      - ./scripts/exploits:/service/exploits/
      - ./configs/config.yml:/service/config.yml
    extra_hosts:
      - "naliway:172.17.0.1"
    networks:
      - service-net

  news:
    image: explabs/ad-ctf-paas-news
    container_name: news
    restart: unless-stopped
    depends_on:
      - rabbit
    environment:
      - ADMIN_PASS=$ADMIN_PASS
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      - TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID
    volumes:
      - ./news:/service/news/
      - ./configs/config.yml:/service/config.yml
    networks:
      - service-net

  malwaretotal:
    image: explabs/malwaretotal
    container_name: malwaretotal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.malwaretotal.rule=Host(`malwaretotal.${DOMAIN}`)"
    volumes:
      - ./configs/malwares.yml:/app/malwares.yml
    networks:
      - proxy

  api:
    build:
      context: ../../ad-ctf-paas-api/
      dockerfile: dev.Dockerfile
    container_name: api
    environment:
      - ADMIN_PASS=${ADMIN_PASS}
      - SERVER_IP=${SERVER_IP}
      - OVPN_ADMIN=http://openvpn:9000
      - MONGODB=mongo:27017
      - REDIS=redis:6379
    volumes:
#      - ./configs/config.yml:/api/config.yml
      - ../../ad-ctf-paas-api/:/api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.${DOMAIN}`)"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
    depends_on:
      - mongo
      - redis
      - ovpn-admin
      - openvpn
      - fileserver
      - rabbit
    networks:
      - service-net
      - vpn-net
      - proxy

  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${ADMIN_PASS}
    volumes:
      - mongo-data:/data/db
    networks:
      - service-net

  redis:
    image: redis:6.2-alpine
    container_name: redis
    command: redis-server --requirepass ${ADMIN_PASS}
    volumes:
      - redis-data:/data/
    networks:
      - service-net

  openvpn:
    image: flant/ovpn-admin:openvpn-1.7.5
    container_name: openvpn
    command: /etc/openvpn/setup/configure.sh
    cap_add:
      - NET_ADMIN
    volumes:
      - ./openvpn/setup/openvpn.conf:/etc/openvpn/setup/openvpn.conf
      - ovpn-easyrsa:/etc/openvpn/easyrsa
      - ovpn-ccd:/etc/openvpn/ccd
      - ovpn-stats:/tmp/openvpn-status.log
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ovpn-admin.rule=Host(`vpn-admin.${DOMAIN}`)"
      - "traefik.http.services.ovpn-admin.loadbalancer.server.port=9000"
      - "traefik.http.routers.ovpn-admin.middlewares=auth"
      - "traefik.tcp.routers.openvpn.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.openvpn.entrypoints=openvpn"
      - "traefik.tcp.routers.openvpn.service=openvpn"
      - "traefik.tcp.services.openvpn.loadbalancer.server.port=1194"
    networks:
      - vpn-net

  openvpn-exporter:
    image:  kumina/openvpn-exporter
    command: -openvpn.status_paths /tmp/openvpn-status.log
    ports:
      - "9176:9176"
    volumes:
      - ovpn-stats:/tmp/openvpn-status.log

  ovpn-admin:
    image: flant/ovpn-admin:1.7.5
    container_name: ovpn-admin
    command: /app/ovpn-admin --listen.port="9000" --ovpn.server="openvpn.${DOMAIN}:1194:tcp" --easyrsa.path="/mnt/easyrsa" --easyrsa.index-path="/mnt/easyrsa/pki/index.txt" --ccd --ccd.path="/mnt/ccd" --auth.password --auth.db="/mnt/easyrsa/pki/users.db"
    network_mode: service:openvpn
    volumes:
      - ovpn-easyrsa:/mnt/easyrsa
      - ovpn-ccd:/mnt/ccd

  fileserver:
    image: explabs/fileserver
    container_name: fileserver
    volumes:
      - ./tasks:/tasks
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fileserver.rule=Host(`fileserver.${DOMAIN}`)"
    restart: unless-stopped
    networks:
      - proxy

volumes:
  mongo-data:
  redis-data:
  ovpn-ccd:
  ovpn-easyrsa:
  ovpn-stats:

networks:
  vpn-net:
  service-net:
  proxy:
