global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: checker
    metrics_path: api/v1/game/checker
    static_configs:
      - targets:
          - 192.168.100.105:8080
    basic_auth:
      username: 'checker'
      password: 'test'

  - job_name: exploit
    metrics_path: api/v1/game/exploit
    scrape_interval: 1m
    scrape_timeout: 10s
    static_configs:
      - targets:
          - 192.168.100.105:8080
    basic_auth:
      username: 'checker'
      password: 'test'

  - job_name: news
    metrics_path: api/v1/game/news
    scrape_interval: 1m
    scrape_timeout: 10s
    static_configs:
      - targets:
          - 192.168.100.105:8080
    basic_auth:
      username: 'checker'
      password: 'test'