#cloud-config
# vim: syntax=yaml
hostname: ${host_name}
manage_etc_hosts: true
users:
  - name: ${name}
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${auth_key}
    shell: /bin/bash
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
runcmd:
  - wget -qO- https://get.docker.com/ | sh
  - usermod -aG docker ${name}
  # Install docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) > /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  # Install autocompletion
  - curl -L https://raw.githubusercontent.com/docker/compose/1.29.2/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose
  - curl -s http://10.0.0.10/file.tgz | tar xvf - -C dest/
ssh_pwauth: false
disable_root: true
power_state:
  mode: reboot
  message: Restarting after installing docker & docker-compose